# Site settings
title: "Active Directory"
bye_message: "*ss*"
baseurl: "/scripts/"
url: "https://HarshSankhala23.github.io"
disqus: HarshSankhala23

# Header settings
Raj: "HarshSankhala23"
source_code:
    server: "github.com"
    Raj: "HarshSankhala23"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
